/*
* generated by Xtext
*/
package de.itemis.xtext.showcases.cityplanning.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class CityDslOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
