/*
 * generated by Xtext
 */
package de.itemis.xtext.showcases.cityplanning;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CityDslRuntimeModule extends de.itemis.xtext.showcases.cityplanning.AbstractCityDslRuntimeModule {

}
