/*
* generated by Xtext
*/
package de.itemis.xtext.showcases.cityplanning.ui.contentassist;

import de.itemis.xtext.showcases.cityplanning.ui.contentassist.AbstractCityDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class CityDslProposalProvider extends AbstractCityDslProposalProvider {

}
