/*
 * generated by Xtext
 */
package de.itemis.xtext.showcases.cityplanning.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CityDslUiModule extends de.itemis.xtext.showcases.cityplanning.ui.AbstractCityDslUiModule {
	public CityDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
